# Generated by Django 5.0.1 on 2024-02-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField()),
                ('logo', models.ImageField(upload_to='site_image/')),
                ('currency', models.CharField(choices=[('uan', '₴'), ('usd', '$'), ('euro', '€')], default='usd')),
                ('email', models.EmailField(max_length=254)),
                ('stripe_private_key', models.CharField(max_length=400)),
                ('stripe_public_key', models.CharField(max_length=400)),
                ('about_us_title', models.CharField()),
                ('about_us_description', models.TextField()),
                ('about_us_image', models.ImageField(upload_to='site_image/')),
            ],
        ),
    ]
