# Generated by Django 5.0.1 on 2024-02-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='about_us_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='about_us_title',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='currency',
            field=models.CharField(blank=True, choices=[('uan', '₴'), ('usd', '$'), ('euro', '€')], default='usd', null=True),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='site_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='stripe_private_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
