# Generated by Django 5.0.1 on 2024-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_detail', '0002_alter_sitedetail_about_us_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site_image/'),
        ),
    ]
