# Generated by Django 5.0.1 on 2024-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
