# Generated by Django 5.0.1 on 2024-02-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportrequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
