# Generated by Django 5.0.1 on 2024-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportrequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='response_send',
            field=models.BooleanField(default=False),
        ),
    ]
