# Generated by Django 5.0.1 on 2024-01-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='goods',
        ),
        migrations.AddField(
            model_name='basket',
            name='goods',
            field=models.ManyToManyField(related_name='basket', to='basket.goods'),
        ),
    ]
