# Generated by Django 5.0.1 on 2024-02-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimages_options_alter_discount_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['id']},
        ),
    ]
